### ISSUE TITLE
Missing keyswitch images for the 11/70

### ISSUE THREAD

**Issue by mdoege** [j-hoppe/BlinkenBone#1]
The 11/70 Java panel does not work because it is missing some images:
```
# java -classpath panelsim_all.jar blinkenbone.panelsim.panelsim1170.Panelsim1170_app
Dez. 05, 2017 5:54:17 NACHM. blinkenbone.panelsim.ResourceManager createBufferedImage
SCHWERWIEGEND: unable to access image file: blinkenbone/panelsim/panelsim1170/images/pdp1170_size=1000_keyswitch_off.png
Dez. 05, 2017 5:54:17 NACHM. blinkenbone.panelsim.ResourceManager createBufferedImage
SCHWERWIEGEND: class path is: panelsim_all.jar
java.lang.NullPointerException
	at blinkenbone.panelsim.ControlSliceStateImage.<init>(Unknown Source)
	at blinkenbone.panelsim.ControlSliceVisualization.addStateImage(Unknown Source)
	at blinkenbone.panelsim.ControlSliceVisualization.addStateImage(Unknown Source)
	at blinkenbone.panelsim.MultiStateControlSliceVisualization.loadStateImages(Unknown Source)
	at blinkenbone.panelsim.ControlSliceVisualization.createStateImages(Unknown Source)
	at blinkenbone.panelsim.panelsim1170.Panel1170.loadControlVisualizationImages(Unknown Source)
	at blinkenbone.panelsim.panelsim1170.Panelsim1170_app$5.actionPerformed(Unknown Source)
	at java.desktop/javax.swing.JComboBox.fireActionEvent(JComboBox.java:1264)
	at java.desktop/javax.swing.JComboBox.setSelectedItem(JComboBox.java:589)
	at java.desktop/javax.swing.JComboBox.setSelectedIndex(JComboBox.java:624)
	at blinkenbone.panelsim.panelsim1170.Panelsim1170_app.initialize(Unknown Source)
	at blinkenbone.panelsim.panelsim1170.Panelsim1170_app.<init>(Unknown Source)
	at blinkenbone.panelsim.panelsim1170.Panelsim1170_app$1.run(Unknown Source)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.desktop/java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:717)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:711)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:89)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:199)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```
I had to copy them over from the 11/20 directory, rename them, and rebuild panelsim_all.jar. Please fix. :-)

**Comment by NeoChen1024** [comment]
I have this problem too, there is only 2950-pixel version for these image.

**Comment by j-hoppe** [comment]
Added the PDP-11/70 keyswitch images. OK now?
